### ISSUE TITLE
[Enhancement] Specify work library

### ISSUE THREAD

**Issue by amal-khailtash** [themperek/cocotb-test#135]
Currently, cocotb-test simulator.run does not provide a way to specify the simulator work library name and it assumes library name is the top_level name.  I could not find a way to get around this.  If there is no workaround, it would be great if one could specify the library name and default to "**work**".

**Comment by themperek** [comment]
Maybe could support a syntax like:
```python3
verilog_sources = {"work":["a,v",b.v"], "zyx": ["z,v","x.v"]}
```
and compile to different libraries if needed.

**Comment by amal-khailtash** [comment]
Yes, that will be great.

**Comment by themperek** [comment]
Should be done in #168
