### ISSUE TITLE
pip install fails on branch cocotb_1p5

### ISSUE THREAD

**Issue by sjalloq** [themperek/cocotb-test#136]
I'm trying to `pip install` the 1.5 branch and it's failing on the dependency check.  I've got 1.5 installed as shown below.  Any poniters as to what is wrong?

```
ERROR: Could not find a version that satisfies the requirement cocotb>=1.5 (from cocotb-test)
ERROR: No matching distribution found for cocotb>=1.5
(venv) [ShareefJalloq@asic cocotb-test]$ pip list | grep cocotb
cocotb             1.5.0.dev305+g427a0af
```

**Comment by sjalloq** [comment]
Same with 1.5.0rc3

**Comment by themperek** [comment]
We need a release that should happen today. Or ignore those dependencies.

**Comment by sjalloq** [comment]
How can I force the install?  Is this just a pip issue in how it checks a version flag somewhere?

**Comment by sjalloq** [comment]
Sorry, should have RTFM: `--no-deps`.
