### ISSUE TITLE
Support multiple top-level designs

### ISSUE THREAD

**Issue by benbr8** [themperek/cocotb-test#158]
Sometimes it is necessary to have multiple top-level designs loaded alongside each other in a simulation.

One example would be `glbl.v` (a global reset module used in some IP targeting Xilinx FPGAs), see https://support.xilinx.com/s/article/6537?language=en_US.

This could be implemented by optionally passing a list to the `toplevel` parameter. I could code and test this for Questa and Icarus, if you agree with this approach.

**Comment by themperek** [comment]
Closed with  #177.

@benbr8 Could you update README.md https://github.com/themperek/cocotb-test#arguments-for-simulatorrun ?

**Comment by benbr8** [comment]
#178 

Thanks for your support
