### ISSUE TITLE
HDL specific compile args for mixed language simulations

### ISSUE THREAD

**Issue by benbr8** [themperek/cocotb-test#159]
Sorry for opening many tickets recently, I'm trying to move all our test cases to cocotb-test. I hope you don't mind.

For mixed language simulations, sometimes different compiler arguments are needed for different languages. One example would be the `-2008` flag which is valid for Questa `vcom` but not for `vlog`.

I'm proposing to add optional `vhdl_compile_args` and `verilog_compile_args` parameters to `simulator.run()`. Let me know what you think.

**Comment by themperek** [comment]
Yes. Do not see a better way for now.

**Comment by benbr8** [comment]
Added in #170.
