### ISSUE TITLE
Unable to generate wave file

### ISSUE THREAD

**Issue by TomO700** [themperek/cocotb-test#187]
Hi,

Ive been trying to generate a wave file using the following command in either .vcd or .fst form, how ever the file doesn't seem to be getting generated.
For fst,
`SIM=verilator EXTRA_ARGS="+= --trace-fst --trace-structs" python test_ob.py`
For vcd
`SIM=verilator EXTRA_ARGS="--trace --trace-structs" python test_ob.py`
`SIM=verilator WAVES=1 python test_ob.py`

Can someone please help. In a bit of hurry.

Thanks!

**Comment by themperek** [comment]
If I do `WAVES=1 SIM=verilator python test_dff.py` I get waves in ` sim_build/dump.fst`

**Comment by TomO700** [comment]
Did the command just as you have typed above, still no .fst
Any suggestions?
