### ISSUE TITLE
Cocotb Error

### ISSUE THREAD

**Issue by TomO700** [themperek/cocotb-test#191]
Hi, 

I keep getting the following error on 3 different versions of cocotb. What could be the possible cause?
`_**CRITICAL Failed to import module <module name>: No module named 'cocotb.drivers'**_`

How can this be fixed?

Thanks

**Comment by themperek** [comment]
`pip install cocotb-bus` ?

**Comment by TomO700** [comment]
Sorry I forgot to close the issue. I did this, but had to do some other tweaks too. It did not work on its own.
