### ISSUE TITLE
'log' command is not supported in the VSimSA DO Mode for Active HDL

### ISSUE THREAD

**Issue by jackbpdx** [themperek/cocotb-test#193]
There is a syntax error with the 'log' command so it needs to be changed to the 'trace' command.  [https://www.aldec.com/resources/manuals/Active-HDL/cmd00086.htm](url)

**Comment by themperek** [comment]
Need more details.

**Comment by jackbpdx** [comment]
In the documentation it states that the log command is not supported in DO mode. 
![1](https://user-images.githubusercontent.com/103971868/183515485-2dc1f14c-0b90-42a2-837f-c901d63a4695.PNG)

**Comment by themperek** [comment]
It is this?
https://github.com/themperek/cocotb-test/blob/ab9e3eaab10ab033949094ea6503b5be19589396/cocotb_test/simulator.py#L938

Can you change and provide PR? It is a bit difficult with the license for me at the moment.

**Comment by jackbpdx** [comment]
That line is referring to Riviera but I'm referring to Active -HDL. 
https://github.com/themperek/cocotb-test/blob/ab9e3eaab10ab033949094ea6503b5be19589396/cocotb_test/simulator.py#L1022

However, I'm sure Riviera has the same issue. 
What is PR?

**Comment by themperek** [comment]
>That line is referring to Riviera but I'm referring to Active -HDL.

How it should look like to make it work?

PR -> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests
