### ISSUE TITLE
Incorrect cmd_build creation for VCS

### ISSUE THREAD

**Issue by alina-andreevna** [themperek/cocotb-test#240]
1. top level module name is not provided in cmd_build line. This is potential problem for simulation when user top module is not matched than found in compile list by vcs
2. timescale parameter syntax in vcs timescale=1ns/1ps, not timescale 1ns/1ps. Also it should be part of cmd_build, not common cmd

**Comment by alina-andreevna** [comment]
I have a patch for this, but can not publish my branch:
```
ERROR: Permission to themperek/cocotb-test.git denied to alina-andreevna.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights     
and the repository exists.
```

**Comment by themperek** [comment]
You need to fork this git repository and commit there and open pull request. Worst case province the code here.

**Comment by themperek** [comment]
Close with https://github.com/themperek/cocotb-test/pull/244
