### ISSUE TITLE
Verilator wave simulation requires c++20

### ISSUE THREAD

**Issue by builderdev212** [themperek/cocotb-test#254]
I've ran into an issue with verilator versions 5.018 and 5.020 with generating waves. It appears they're using features supported in C++20 and newer, therefore tests fail when attempting to run them by default with wave generation on currently. Was wondering if anyone else has ran into this issue, and if I should make a pr with my fix?

**Comment by themperek** [comment]
Is there any error? 

You can try to set the environmental variable `CXXFLAGS` to `-std=c++20`
