### ISSUE TITLE
marge results xml of all test in some smart way

### ISSUE THREAD

**Issue by themperek** [themperek/cocotb-test#37]

**Comment by cmarqu** [comment]
Do you have more in mind than https://github.com/cocotb/cocotb/blob/master/bin/combine_results.py ?

**Comment by themperek** [comment]
Something equivalent but here seems a pytest plugin will be needed.

**Comment by themperek** [comment]
It looks like a python plugin that will collect all the results files would best (assuming one run in one test). 
Seems there is no 'satisfy all' solution here.

**Comment by themperek** [comment]
Some initial possible idea #39
