### ISSUE TITLE
No mutable objects as default values

### ISSUE THREAD

**Issue by andresdemski** [themperek/cocotb-test#47]
Hi!

I found that `Simulator`'s arguments are initialized with '`[]`. It's not a good idea because it can produce an unexpected behavior.

Example:

```python
In [271]: class MyClass: 
     ...:     def __init__(self, arg=[]): 
     ...:         arg.append('bleee') 
     ...:         print(arg) 
     ...:                                                                          

In [272]: a = MyClass()                                                            
['bleee']

In [273]: b = MyClass()                                                            
['bleee', 'bleee']
```

**Comment by cmarqu** [comment]
Indeed: https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments

Maybe we should start maintaining cocotb-test as a cocotb branch and find stuff like this with its CI setup which includes LGTM?

**Comment by themperek** [comment]
Should be fixed now. Thank you!
