### ISSUE TITLE
Support passing a working directory to the call to cocotb

### ISSUE THREAD

**Issue by markmelvin** [themperek/cocotb-test#61]
Currently the cocotb build is run with a working directory of `sim_build`. This is different than when cocotb is run with `make -C working_dir`. It would be good to be able to pass the working directory to the spawned cocotb process as an argument.

**Comment by themperek** [comment]
Adding and passing a `run_dir` here: https://github.com/themperek/cocotb-test/blob/master/cocotb_test/simulator.py#L52 may work. If this works let me know I can change propose PR.
